- name: Create ec2 instance and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-063f4a8b92c8783d5"
    zone_id: "Z10433352FG8G3570MODR"
    domain_name: "daws86s.art"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instace:
    name: " {{ item }}"
    instance_type: t3.micro
    security_group: "{{ sg_id }}"
    image_id: " {{ ami_id }}"
    tags:
      Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output


  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
