- name: Create ec2 instance and r53
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-07b0ccbd6b371acca"
    region: us-east-1
    instances:
      - mongodb

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: Print EC2 output
      ansible.builtin.debug:
        var: ec2_output
